# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phoneno', models.CharField(max_length=12)),
                ('mobileno', models.CharField(max_length=15)),
                ('network', models.CharField(max_length=30)),
                ('television', models.CharField(max_length=30)),
                ('tvchannels', models.CharField(max_length=30)),
                ('newschannels', models.CharField(max_length=30)),
                ('refrigerator', models.CharField(max_length=30)),
                ('twowheelers', models.CharField(max_length=30)),
                ('tractor', models.CharField(max_length=30)),
                ('soap', models.CharField(max_length=30)),
                ('shampoo', models.CharField(max_length=30)),
                ('detergantbar', models.CharField(max_length=30)),
                ('detergantpowder', models.CharField(max_length=30)),
            ],
        ),
    ]
